const skills = {
    "miecze": { "gp": 30, "koszt": 100, "long": "walce mieczem" },
    "szable": { "gp": 30, "koszt": 100, "long": "walce szabla" },
    "sztylety": { "gp": 30, "koszt": 70, "long": "walce sztyletem" },
    "topory": { "gp": 30, "koszt": 100, "long": "walce toporem" },
    "znajomosc jezykow": { "gp": 40, "koszt": 50, "long": "identyfikacji starozytnych i wspolczesnych jezykow i pism" },
    "maczugi": { "gp": 30, "koszt": 100, "long": "walce maczuga" },
    "mloty": { "gp": 30, "koszt": 100, "long": "walce mlotem" },
    "bronie drzewcowe": { "gp": 30, "koszt": 100, "long": "walce bronia drzewcowa" },
    "wlocznie": { "gp": 30, "koszt": 100, "long": "walce wlocznia" },
    "bicze": { "gp": 30, "koszt": 40, "long": "walce biczem" },
    "zielarstwo": { "gp": 100, "koszt": 70, "long": "znajdowaniu i rozpoznawaniu ziol" },
    "bronie lancuchowe": { "gp": 30, "koszt": 100, "long": "walce bronmi lanuchowymi" },
    "alchemia": { "gp": 100, "koszt": 70, "long": "warzeniu i rozpoznawaniu mikstur" },
    "luki": { "gp": 30, "koszt": 70, "long": "poslugiwaniu sie lukami" },
    "skradanie sie": { "gp": 30, "koszt": 70, "long": "przemykaniu sie ukradkiem" },
    "przemiana": { "gp": 30, "koszt": 100, "long": "poslugiwaniu sie magia przemiany" },
    "kusze": { "gp": 30, "koszt": 70, "long": "poslugiwaniu sie kuszami" },
    "ukrywanie sie": { "gp": 30, "koszt": 70, "long": "ukrywaniu siebie i przedmiotow" },
    "iluzja": { "gp": 30, "koszt": 100, "long": "poslugiwaniu sie magia iluzji" },
    "mistycyzm": { "gp": 30, "koszt": 100, "long": "mistycyzmie" },
    "wyczucie slabosci": { "gp": 20, "koszt": 200, "long": "wyczuwaniu slabosci wroga" },
    "zaklinanie": { "gp": 30, "koszt": 100, "long": "zaklinaniu" },
    "przywolywanie": { "gp": 30, "koszt": 100, "long": "magii tworzenia i przywolywania" },
    "rozpraszanie": { "gp": 30, "koszt": 100, "long": "rozpraszaniu zaklec" },
    "walka dwiema bronmi": { "gp": 20, "koszt": 100, "long": "walce dwiema bronmi jednoczesnie" },
    "walka bez broni": { "gp": 30, "koszt": 50, "long": "walce bez broni" },
    "walka w ciemnosci": { "gp": 20, "koszt": 50, "long": "walce w ciemnosciach" },
    "parowanie": { "gp": 20, "koszt": 100, "long": "parowaniu ciosow przeciwnika" },
    "uniki": { "gp": 20, "koszt": 100, "long": "unikaniu ciosow przeciwnika" },
    "walka konna": { "gp": 30, "koszt": 70, "long": "walce z konskiego grzbietu" },
    "tarczownictwo": { "gp": 20, "koszt": 100, "long": "skutecznym uzywaniu tarczy" },
    "ogluszanie": { "gp": 20, "koszt": 50, "long": "ogluszaniu przeciwnikow" },
    "zdolnosci przywodcze": { "gp": 30, "koszt": 130, "long": "wywieraniu wplywu na innych" },
    "walka w szyku": { "gp": 30, "koszt": 80, "long": "walce w szyku" },
    "ocena przeciwnika": { "gp": 30, "koszt": 50, "long": "ocenianiu cech i stanow osob" },
    "ocena obiektu": { "gp": 30, "koszt": 50, "long": "ocenianiu wlasnosci przedmiotow" },
    "szacowanie": { "gp": 30, "koszt": 50, "long": "szacowaniu wartosci przedmiotow" },
    "plywanie": { "gp": 50, "koszt": 50, "long": "plywaniu i nurkowaniu" },
    "wspinaczka": { "gp": 50, "koszt": 50, "long": "wspinaniu sie" },
    "opieka nad zwierzetami": { "gp": 30, "koszt": 50, "long": "opiekowaniu sie zwierzetami i wzbudzaniu ich zaufania" },
    "wyczucie kierunku": { "gp": 30, "koszt": 50, "long": "rozpoznawaniu kierunkow i znajdowaniu sciezek" },
    "tropienie": { "gp": 30, "koszt": 60, "long": "znajdowaniu i rozpoznawaniu sladow" },
    "lowiectwo": { "gp": 100, "koszt": 50, "long": "lowieniu dzikich zwierzat" },
    "magia ognia": { "gp": 30, "koszt": 100, "long": "poslugiwaniu sie magia ognia" },
    "spostrzegawczosc": { "gp": 50, "koszt": 60, "long": "zauwazaniu tego, co ukryte" },
    "magia powietrza": { "gp": 30, "koszt": 100, "long": "poslugiwaniu sie magia powietrza" },
    "targowanie sie": { "gp": 30, "koszt": 100, "long": "zawieraniu korzystnych transakcji handlowych" },
    "magia ziemi": { "gp": 30, "koszt": 100, "long": "poslugiwaniu sie magia ziemi" },
    "jezdziectwo": { "gp": 35, "koszt": 55, "long": "jezdzie konnej" },
    "magia wody": { "gp": 30, "koszt": 100, "long": "poslugiwaniu sie magia wody" },
    "gornictwo": { "gp": 100, "koszt": 90, "long": "wydobywaniu mineralow spod ziemi" },
    "magia zycia": { "gp": 30, "koszt": 100, "long": "poslugiwaniu sie magia zycia" },
    "magia mroku": { "gp": 30, "koszt": 100, "long": "poslugiwaniu sie magia mroku" },
    "metalurgia": { "gp": 100, "koszt": 60, "long": "metalurgii" },
    "zestrojenie ze slowami runicznymi": { "gp": 100, "koszt": 100, "long": "zestrojeniu ze slowami runicznymi" },
    "koncentracja": { "gp": 30, "koszt": 100, "long": "koncentrowaniu swoich magicznych zdolnosci" },
    "koncentracja w walce": { "gp": 20, "koszt": 100, "long": "koncentrowaniu swoich magicznych zdolnosci podczas walki" },
    "magia runiczna": { "gp": 30, "koszt": 70, "long": "pisaniu i uzywaniu run" },
    "czarodziejstwo": { "gp": 30, "koszt": 70, "long": "znajomosci i uzywaniu magii" },
}
