const skillsGp = {
    "miecze": 30,
    "szable": 30,
    "sztylety": 30,
    "topory": 30,
    "znajomosc jezykow": 40,
    "maczugi": 30,
    "mloty": 30,
    "bronie drzewcowe": 30,
    "wlocznie": 30,
    "bicze": 30,
    "zielarstwo": 100,
    "bronie lancuchowe": 30,
    "alchemia": 100,
    "luki": 30,
    "skradanie sie": 30,
    "przemiana": 30,
    "kusze": 30,
    "ukrywanie sie": 30,
    "iluzja": 30,
    "mistycyzm": 30,
    "wyczucie slabosci": 20,
    "zaklinanie": 30,
    "przywolywanie": 30,
    "rozpraszanie": 30,
    "walka dwiema bronmi": 20,
    "walka bez broni": 30,
    "walka w ciemnosci": 20,
    "parowanie": 20,
    "uniki": 20,
    "walka konna": 30,
    "tarczownictwo": 20,
    "ogluszanie": 20,
    "zdolnosci przywodcze": 30,
    "walka w szyku": 30,
    "ocena przeciwnika": 30,
    "ocena obiektu": 30,
    "szacowanie": 30,
    "plywanie": 50,
    "wspinaczka": 50,
    "opieka nad zwierzetami": 30,
    "wyczucie kierunku": 30,
    "tropienie": 30,
    "lowiectwo": 100,
    "magia ognia": 30,
    "spostrzegawczosc": 50,
    "magia powietrza": 30,
    "targowanie sie": 30,
    "magia ziemi": 30,
    "jezdziectwo": 35,
    "magia wody": 30,
    "gornictwo": 100,
    "magia zycia": 30,
    "magia mroku": 30,
    "metalurgia": 100,
    "zestrojenie ze slowami runicznymi": 100,
    "koncentracja": 30,
    "koncentracja w walce": 20,
    "magia runiczna": 30,
    "czarodziejstwo": 30,
};
