// Skill mapping for display
        const skillDisplayMapping = {
            "miecze": "Miecze",
            "sztylety": "Sztylety",
            "walke dwiema bronmi": "Walka dwiema brońmi",
            "parowanie": "Parowanie",
            "uniki": "Uniki",
            "ocene przeciwnika": "Ocena przeciwnika",
            "ocene obiektu": "Ocena obiektu",
            "opieke nad zwierzetami": "Opieka nad zwierzętami",
            "spostrzegawczosc": "Spostrzegawczość",
            "jezdziectwo": "Jeździectwo",
            "znajomosc jezykow": "Znajomość języków",
            "fechtunek": "Fechtunek",
            "maczugi": "Maczugi",
            "koncentracje": "Koncentracja",
            "koncentracje w walce": "Koncentracja w walce",
            "rozpraszanie": "Rozpraszanie",
            "mloty": "Młoty",
            "bronie drzewcowe": "Bronie drzewcowe",
            "wyczucie kierunku": "Wyczucie kierunku",
            "magie mroku": "Magia mroku",
            "iluzje": "Iluzje",
            "tarczownictwo": "Tarczownictwo",
            "manewry bojowe": "Manewry bojowe",
            "szable": "Szable",
            "tropienie": "Tropienie",
            "skradanie sie": "Skradanie się",
            "ukrywanie sie": "Ukrywanie się",
            "wyczucie slabosci": "Wyczucie słabości",
            "rzut piaskiem": "Rzut piaskiem",
            "ciecie": "Cięcie",
            "topory": "Topory",
            "szacowanie": "Szacowanie",
            "regeneracje": "Regeneracja",
            "odpornosc": "Odporność",
            "chlasniecie": "Chlaśnięcie",
            "wlocznie": "Włócznie",
            "taniec broni": "Taniec broni",
            "walke w ciemnosci": "Walka w ciemności",
            "walke w szyku": "Walka w szyku",
            "plywanie": "Pływanie",
            "wspinaczke": "Wspinaczka",
            "riposte": "Riposta",
            "bronie lancuchowe": "Bronie łańcuchowe",
            "uderzenie tarcza": "Uderzenie tarczą",
            "gwardyjski cios": "Gwardyjski cios",
            "walke bez broni": "Walka bez broni",
            "zwinny cios": "Zwinny cios",
            "przemiane": "Przemiana",
            "przywolywanie": "Przywoływanie",
            "magie ognia": "Magia ognia",
            "magie powietrza": "Magia powietrza",
            "magie ziemi": "Magia ziemi",
            "magie wody": "Magia wody",
            "magie runiczna": "Magia runiczna",
            "czarodziejstwo": "Czarodziejstwo",
            "zaklinanie": "Zaklinanie",
            "niematerialne ciecie": "Niematerialne cięcie"
        };