const slowaData = [
    {
        "name": "wybraniec losu",
        "cost": 10,
        "runes": ["Ko", "Dol", "El"],
        "description": "podnosi zauwazalnie prawdopodobienstwo zdobycia lepszych run",
        "effects": [
            ["_pb_prop", "_live_i_rune_extra_levels", 3],
        ],
    },
    {
        "name": "widzacy",
        "cost": 10,
        "runes": ["Sol", "Tir", "Ral"],
        "description": "podnosi troche umiejetnosc w ocenianiu wlasnosci przedmiotow, troche umiejetnosc w szacowaniu wartosci przedmiotow oraz sporo widzenie w ciemnosci ponadto pozwala widziec magiczna energie",
        "effects": [
            ["_pb_skill", 101, 20],
            ["_pb_skill", 102, 20],
            ["_pb_prop", "_live_i_see_dark", 4],
            ["_pb_prop", "_live_i_see_magic", 100],
        ],
    },
    {
        "name": "leniuszek",
        "cost": 20,
        "runes": ["Nef", "Hel", "Ko"],
        "description": "podnosi troche umiejetnosc w ocenianiu wlasnosci przedmiotow ponadto juz nigdy nie bedziesz musial odwiedzac kowala",
        "effects": [
            ["_pb_skill", 101, 20],
            ["_pb_prop", "_player_i_have_leniuch", 1],
        ],
    },
    {
        "name": "duzo wiecej",
        "cost": 10,
        "runes": ["Ort", "Hel", "Io"],
        "description": "podnosi zauwazalnie prawdopodobienstwo zdobycia dodatkowych run",
        "effects": [
            ["_pb_prop", "_live_i_rune_extra_chance", 150],
        ],
    },
    {
        "name": "jajoglowy",
        "cost": 10,
        "runes": ["Sol", "Tal", "Thul"],
        "description": "podnosi sporo ilosc zapamietanych czarow oraz nieco wielkosc listy dozwolonych czarow",
        "effects": [
            ["_pb_prop", "_live_i_extra_remembered_spells", 6],
            ["_pb_prop", "_live_i_extra_auto_cast", 3],
        ],
    },
    {
        "name": "spekulant",
        "cost": 20,
        "runes": ["Thul", "Ort", "Amn"],
        "description": "podnosi troche umiejetnosc w zawieraniu korzystnych transakcji handlowych",
        "effects": [
            ["_pb_skill", 110, 20],
        ],
    },
    {
        "name": "profesor",
        "cost": 20,
        "runes": ["Dol", "Tir", "Tal"],
        "description": "podnosi nieznacznie ilosc doswiadczenia przekazywanego na inteligencje oraz nieznacznie ilosc doswiadczenia przekazywanego na madrosc",
        "effects": [
            ["_pb_prop", "_live_i_extra_exp_modifier_3", 1500],
            ["_pb_prop", "_live_i_extra_exp_modifier_4", 1500],
        ],
    },
    {
        "name": "miesniak",
        "cost": 20,
        "runes": ["El", "Ral", "Dol"],
        "description": "podnosi minimalnie ilosc doswiadczenia przekazywanego na sile, minimalnie ilosc doswiadczenia przekazywanego na zrecznosc oraz minimalnie ilosc doswiadczenia przekazywanego na wytrzymalosc",
        "effects": [
            ["_pb_prop", "_live_i_extra_exp_modifier_0", 1000],
            ["_pb_prop", "_live_i_extra_exp_modifier_1", 1000],
            ["_pb_prop", "_live_i_extra_exp_modifier_2", 1000],
        ],
    },
    {
        "name": "heros",
        "cost": 20,
        "runes": ["Tal", "Hel", "Amn"],
        "description": "podnosi nieznacznie ilosc doswiadczenia przekazywanego na odwage",
        "effects": [
            ["_pb_prop", "_live_i_extra_exp_modifier_5", 2000],
        ],
    },
    {
        "name": "kopacz",
        "cost": 10,
        "runes": ["El", "Amn", "Ith"],
        "description": "podnosi troche umiejetnosc w wydobywaniu mineralow spod ziemi",
        "effects": [
            ["_pb_skill", 112, 20],
        ],
    },
    {
        "name": "wytapiacz",
        "cost": 10,
        "runes": ["Amn", "Eld", "Eth"],
        "description": "podnosi troche umiejetnosc w metalurgii",
        "effects": [
            ["_pb_skill", 114, 20],
        ],
    },
    {
        "name": "kolekcjoner",
        "cost": 20,
        "runes": ["Tir", "Dol", "Ort"],
        "description": "podnosi nieznacznie ilosc przedmiotow ktore mozesz trwale zabezpieczyc",
        "effects": [
            ["_pb_prop", "_live_i_allowed_keep_forever", 1],
        ],
    },
    {
        "name": "szczesciarz",
        "cost": 10,
        "runes": ["Ith", "Tir", "Eld"],
        "description": "podnosi nieco prawdopodobienstwo zdobycia lepszych run",
        "effects": [
            ["_pb_prop", "_live_i_rune_extra_levels", 2],
        ],
    },
    {
        "name": "wiecej",
        "cost": 10,
        "runes": ["El", "Eth", "Nef"],
        "description": "podnosi nieco prawdopodobienstwo zdobycia dodatkowych run",
        "effects": [
            ["_pb_prop", "_live_i_rune_extra_chance", 75],
        ],
    },
    {
        "name": "witalny",
        "cost": 20,
        "runes": ["Shael", "Eld", "Thul"],
        "description": "podnosi ogromnie regeneracje kondycji",
        "effects": [
            ["_pb_prop", "_live_i_hp_regen_increased", 100],
        ],
    },
    {
        "name": "uduchowiony",
        "cost": 20,
        "runes": ["Io", "Ith", "Tir"],
        "description": "podnosi minimalnie regeneracje many",
        "effects": [
            ["_pb_prop", "_live_i_mana_regen_increased", 5],
        ],
    },
    {
        "name": "niezmordowany",
        "cost": 20,
        "runes": ["Eth", "El", "Hel"],
        "description": "podnosi troche regeneracje zmeczenia",
        "effects": [
            ["_pb_prop", "_live_i_fatigue_regen_increased", 40],
        ],
    },
    {
        "name": "farciarz",
        "cost": 20,
        "runes": ["Lum", "Ral", "Dol"],
        "description": "podnosi zauwazalnie szczescie",
        "effects": [
            ["_pb_prop", "_live_i_luck_increased", 50],
        ],
    },
    {
        "name": "silny",
        "cost": 30,
        "runes": ["Tir", "Ort", "Amn"],
        "description": "podnosi nieznacznie sile",
        "effects": [
            ["_pb_stat", 0, 20],
        ],
    },
    {
        "name": "zreczny",
        "cost": 30,
        "runes": ["Amn", "Eth", "El"],
        "description": "podnosi nieznacznie zrecznosc",
        "effects": [
            ["_pb_stat", 1, 20],
        ],
    },
    {
        "name": "wytrzymaly",
        "cost": 30,
        "runes": ["Thul", "Amn", "Eld"],
        "description": "podnosi nieznacznie wytrzymalosc",
        "effects": [
            ["_pb_stat", 2, 20],
        ],
    },
    {
        "name": "inteligentny",
        "cost": 30,
        "runes": ["Eth", "Amn", "Ral"],
        "description": "podnosi nieznacznie inteligencje",
        "effects": [
            ["_pb_stat", 3, 20],
        ],
    },
    {
        "name": "madry",
        "cost": 30,
        "runes": ["Nef", "Ral", "Amn"],
        "description": "podnosi nieznacznie madrosc",
        "effects": [
            ["_pb_stat", 4, 20],
        ],
    },
    {
        "name": "odwazny",
        "cost": 30,
        "runes": ["Amn", "Tal", "Ort"],
        "description": "podnosi nieznacznie odwage",
        "effects": [
            ["_pb_stat", 5, 20],
        ],
    },
    {
        "name": "szampierz",
        "cost": 30,
        "runes": ["Tal", "Eld", "Sol"],
        "description": "podnosi nieznacznie umiejetnosci walki wszystkimi bronmi",
        "effects": [
            ["_pb_skill_weapon", 10],
        ],
    },
    {
        "name": "karateka",
        "cost": 30,
        "runes": ["Tir", "Amn", "Tal"],
        "description": "podnosi nieznacznie umiejetnosc w walce bez broni",
        "effects": [
            ["_pb_skill", 21, 10],
        ],
    },
    {
        "name": "patelnia",
        "cost": 30,
        "runes": ["Eth", "Tal", "Sol"],
        "description": "podnosi nieznacznie umiejetnosc w skutecznym uzywaniu tarczy",
        "effects": [
            ["_pb_skill", 26, 10],
        ],
    },
    {
        "name": "lewak",
        "cost": 30,
        "runes": ["Tal", "Amn", "Ral"],
        "description": "podnosi nieznacznie umiejetnosc w parowaniu ciosow przeciwnika",
        "effects": [
            ["_pb_skill", 23, 10],
        ],
    },
    {
        "name": "wicher",
        "cost": 30,
        "runes": ["Ith", "Ort", "Amn"],
        "description": "podnosi nieznacznie umiejetnosc w unikaniu ciosow przeciwnika",
        "effects": [
            ["_pb_skill", 24, 10],
        ],
    },
    {
        "name": "tancerz",
        "cost": 30,
        "runes": ["Dol", "El", "Ith"],
        "description": "podnosi nieznacznie umiejetnosc w walce dwiema bronmi jednoczesnie",
        "effects": [
            ["_pb_skill", 20, 10],
        ],
    },
    {
        "name": "koniuszy",
        "cost": 30,
        "runes": ["Ort", "Nef", "Thul"],
        "description": "podnosi troche umiejetnosc w walce z konskiego grzbietu",
        "effects": [
            ["_pb_skill", 25, 20],
        ],
    },
    {
        "name": "przyboczny",
        "cost": 30,
        "runes": ["Sol", "Ith", "Nef"],
        "description": "podnosi troche umiejetnosc w walce w szyku",
        "effects": [
            ["_pb_skill", 31, 20],
        ],
    },
    {
        "name": "przywodca",
        "cost": 30,
        "runes": ["Thul", "Hel", "Dol"],
        "description": "podnosi troche umiejetnosc w wywieraniu wplywu na innych",
        "effects": [
            ["_pb_skill", 30, 20],
        ],
    },
    {
        "name": "ogien",
        "cost": 30,
        "runes": ["Shael", "Thul", "Tir"],
        "description": "podnosi nieznacznie umiejetnosc w poslugiwaniu sie magia ognia",
        "effects": [
            ["_pb_skill", 300, 10],
        ],
    },
    {
        "name": "powietrze",
        "cost": 30,
        "runes": ["Ort", "Ith", "Shael"],
        "description": "podnosi nieznacznie umiejetnosc w poslugiwaniu sie magia powietrza",
        "effects": [
            ["_pb_skill", 301, 10],
        ],
    },
    {
        "name": "ziemia",
        "cost": 30,
        "runes": ["Thul", "Shael", "Eld"],
        "description": "podnosi nieznacznie umiejetnosc w poslugiwaniu sie magia ziemi",
        "effects": [
            ["_pb_skill", 302, 10],
        ],
    },
    {
        "name": "woda",
        "cost": 30,
        "runes": ["Shael", "Eth", "El"],
        "description": "podnosi nieznacznie umiejetnosc w poslugiwaniu sie magia wody",
        "effects": [
            ["_pb_skill", 303, 10],
        ],
    },
    {
        "name": "zycie",
        "cost": 30,
        "runes": ["El", "Tir", "Shael"],
        "description": "podnosi nieznacznie umiejetnosc w poslugiwaniu sie magia zycia",
        "effects": [
            ["_pb_skill", 304, 10],
        ],
    },
    {
        "name": "smierc",
        "cost": 30,
        "runes": ["Shael", "Nef", "Ort"],
        "description": "podnosi nieznacznie umiejetnosc w poslugiwaniu sie magia mroku",
        "effects": [
            ["_pb_skill", 305, 10],
        ],
    },
    {
        "name": "przemiana",
        "cost": 30,
        "runes": ["Ith", "Shael", "Tal"],
        "description": "podnosi nieznacznie umiejetnosc w poslugiwaniu sie magia przemiany",
        "effects": [
            ["_pb_skill", 332, 10],
        ],
    },
    {
        "name": "mistycyzm",
        "cost": 30,
        "runes": ["Ort", "Eld", "Shael"],
        "description": "podnosi nieznacznie umiejetnosc w mistycyzmie",
        "effects": [
            ["_pb_skill", 334, 10],
        ],
    },
    {
        "name": "zaklinanie",
        "cost": 30,
        "runes": ["Shael", "Tal", "Tir"],
        "description": "podnosi nieznacznie umiejetnosc w zaklinaniu",
        "effects": [
            ["_pb_skill", 335, 10],
        ],
    },
    {
        "name": "przywolywanie",
        "cost": 30,
        "runes": ["Shael", "Ral", "Nef"],
        "description": "podnosi nieznacznie umiejetnosc w magii tworzenia i przywolywania",
        "effects": [
            ["_pb_skill", 336, 10],
        ],
    },
    {
        "name": "iluzja",
        "cost": 30,
        "runes": ["Nef", "Shael", "Tal"],
        "description": "podnosi nieznacznie umiejetnosc w poslugiwaniu sie magia iluzji",
        "effects": [
            ["_pb_skill", 333, 10],
        ],
    },
    {
        "name": "rozpraszanie",
        "cost": 30,
        "runes": ["Ith", "El", "Shael"],
        "description": "podnosi nieznacznie umiejetnosc w rozpraszaniu zaklec",
        "effects": [
            ["_pb_skill", 337, 10],
        ],
    },
    {
        "name": "czarodziejstwo",
        "cost": 30,
        "runes": ["Eth", "Shael", "Tir"],
        "description": "podnosi nieznacznie umiejetnosc w znajomosci i uzywaniu magii",
        "effects": [
            ["_pb_skill", 313, 10],
        ],
    },
    {
        "name": "runy",
        "cost": 30,
        "runes": ["Eld", "Tal", "Shael"],
        "description": "podnosi nieznacznie umiejetnosc w pisaniu i uzywaniu run",
        "effects": [
            ["_pb_skill", 312, 10],
        ],
    },
    {
        "name": "koncentracja",
        "cost": 30,
        "runes": ["Ith", "Dol", "El"],
        "description": "podnosi nieznacznie umiejetnosc w koncentrowaniu swoich magicznych zdolnosci",
        "effects": [
            ["_pb_skill", 310, 10],
        ],
    },
    {
        "name": "waleczny spokoj",
        "cost": 30,
        "runes": ["Dol", "Nef", "Tal"],
        "description": "podnosi troche umiejetnosc w koncentrowaniu swoich magicznych zdolnosci podczas walki",
        "effects": [
            ["_pb_skill", 311, 20],
        ],
    },
    {
        "name": "wojownik",
        "cost": 50,
        "runes": ["Ral", "Tir", "Nef"],
        "description": "pozwala trenowac umiejetnosci walki wszystkimi bronmi na poprawnie, pozwala trenowac umiejetnosc w skutecznym uzywaniu tarczy na znosnie, pozwala trenowac umiejetnosc w parowaniu ciosow przeciwnika na znosnie oraz pozwala trenowac umiejetnosc w unikaniu ciosow przeciwnika na znosnie",
        "effects": [
            ["_pb_skill_learn_weapon", 60],
            ["_pb_skill_learn", 26, 45],
            ["_pb_skill_learn", 23, 45],
            ["_pb_skill_learn", 24, 45],
        ],
    },
    {
        "name": "mag",
        "cost": 50,
        "runes": ["Eth", "Ral", "Tir"],
        "description": "pozwala trenowac umiejetnosci ze wszystkich szkol magii na powierzchownie, pozwala trenowac umiejetnosc w koncentrowaniu swoich magicznych zdolnosci na poprawnie oraz pozwala trenowac umiejetnosc w koncentrowaniu swoich magicznych zdolnosci podczas walki na znosnie",
        "effects": [
            ["_pb_skill_learn_magic_all", 40],
            ["_pb_skill_learn", 310, 60],
            ["_pb_skill_learn", 311, 50],
        ],
    },
    {
        "name": "galop",
        "cost": 40,
        "runes": ["Eld", "Eth", "Hel"],
        "description": "podnosi zauwazalnie umiejetnosc w jezdzie konnej, sporo umiejetnosc w walce z konskiego grzbietu oraz nieznacznie umiejetnosci walki wszystkimi bronmi",
        "effects": [
            ["_pb_skill", 111, 25],
            ["_pb_skill", 25, 30],
            ["_pb_skill_weapon", 10],
        ],
    },
    {
        "name": "mikstura",
        "cost": 40,
        "runes": ["Dol", "Thul", "Ral"],
        "description": "podnosi troche umiejetnosc w warzeniu i rozpoznawaniu mikstur, troche umiejetnosc w znajdowaniu i rozpoznawaniu ziol oraz nieznacznie umiejetnosc w poslugiwaniu sie magia przemiany",
        "effects": [
            ["_pb_skill", 331, 20],
            ["_pb_skill", 330, 20],
            ["_pb_skill", 332, 10],
        ],
    },
    {
        "name": "berserker",
        "cost": 40,
        "runes": ["Tir", "Lum", "Eth"],
        "description": "podnosi troche umiejetnosci walki wszystkimi bronmi oraz troche umiejetnosc w walce bez broni natomiast obniza nieznacznie umiejetnosc w unikaniu ciosow przeciwnika, nieznacznie umiejetnosc w parowaniu ciosow przeciwnika, nieznacznie umiejetnosc w skutecznym uzywaniu tarczy oraz minimalnie wytrzymalosc",
        "effects": [
            ["_pb_skill_weapon", 20],
            ["_pb_skill", 21, 20],
            ["_pb_skill", 24, -10],
            ["_pb_skill", 23, -10],
            ["_pb_skill", 26, -10],
            ["_pb_stat", 2, -10],
        ],
    },
    {
        "name": "barbarzynca",
        "cost": 40,
        "runes": ["Lum", "Nef", "Ith"],
        "description": "podnosi nieco umiejetnosci walki wszystkimi bronmi, nieco umiejetnosc w walce bez broni, minimalnie umiejetnosc w unikaniu ciosow przeciwnika, minimalnie umiejetnosc w parowaniu ciosow przeciwnika oraz minimalnie umiejetnosc w skutecznym uzywaniu tarczy ponadto blokuje uzywanie jakiekolwiek magii",
        "effects": [
            ["_pb_skill_weapon", 15],
            ["_pb_skill", 21, 15],
            ["_pb_skill", 24, 5],
            ["_pb_skill", 23, 5],
            ["_pb_skill", 26, 5],
            ["_pb_prop", "_live_m_magic_blocked", "Twoja moc uleciala."],
        ],
    },
    {
        "name": "mag bojowy",
        "cost": 40,
        "runes": ["Eth", "Io", "Thul"],
        "description": "podnosi minimalnie umiejetnosci walki wszystkimi bronmi, nieco umiejetnosc w koncentrowaniu swoich magicznych zdolnosci podczas walki, minimalnie umiejetnosc w unikaniu ciosow przeciwnika, minimalnie umiejetnosc w parowaniu ciosow przeciwnika oraz minimalnie umiejetnosc w skutecznym uzywaniu tarczy natomiast obniza nieco wplyw wagi zbroi na czarowanie",
        "effects": [
            ["_pb_skill_weapon", 5],
            ["_pb_skill", 311, 15],
            ["_pb_skill", 24, 5],
            ["_pb_skill", 23, 5],
            ["_pb_skill", 26, 5],
            ["_pb_prop", "_live_i_mage_armour_weight_increased", -25],
        ],
    },
    {
        "name": "tarczownik",
        "cost": 40,
        "runes": ["Io", "Ith", "Ral"],
        "description": "podnosi nieco umiejetnosc w unikaniu ciosow przeciwnika, nieco umiejetnosc w parowaniu ciosow przeciwnika, nieco umiejetnosc w skutecznym uzywaniu tarczy, nieco umiejetnosc w walce w szyku oraz nieco maksymalna kondycje natomiast obniza minimalnie umiejetnosci walki wszystkimi bronmi oraz minimalnie umiejetnosc w walce bez broni",
        "effects": [
            ["_pb_skill_weapon", -5],
            ["_pb_skill", 21, -5],
            ["_pb_skill", 24, 15],
            ["_pb_skill", 23, 15],
            ["_pb_skill", 26, 15],
            ["_pb_skill", 31, 15],
            ["_pb_hp", 1000],
        ],
    },
    {
        "name": "celny",
        "cost": 40,
        "runes": ["Amn", "Ort", "Hel"],
        "description": "podnosi nieznacznie umiejetnosc w walce dwiema bronmi jednoczesnie oraz nieznacznie ilosc obrazen ktore pomijaja zbroje",
        "effects": [
            ["_pb_skill", 20, 10],
            ["_pb_prop", "_live_i_ac_penetration", 20],
        ],
    },
    {
        "name": "szybki",
        "cost": 40,
        "runes": ["Thul", "Hel", "Eld"],
        "description": "podnosi minimalnie zrecznosc oraz nieznacznie szybkosc wyprowadzanych atakow natomiast obniza minimalnie sile oraz nieznacznie umiejetnosc w wyczuwaniu slabosci wroga",
        "effects": [
            ["_pb_stat", 1, 10],
            ["_pb_stat", 0, -10],
            ["_pb_prop", "_live_i_quickness", 20],
            ["_pb_skill", 207, -10],
        ],
    },
    {
        "name": "silacz",
        "cost": 40,
        "runes": ["Fal", "Thul", "Ith"],
        "description": "podnosi minimalnie umiejetnosc w walce dwiema bronmi jednoczesnie oraz nieznacznie regeneracje zmeczenia ponadto pozwala dobywac dwureczne bronie jedna reka",
        "effects": [
            ["_pb_skill", 20, 5],
            ["_pb_prop", "_live_i_allow_wield_2h_in_1h", 2],
            ["_pb_prop", "_live_i_fatigue_regen_increased", 15],
        ],
    },
    {
        "name": "mesmer",
        "cost": 40,
        "runes": ["Sol", "Eth", "Lum"],
        "description": "podnosi nieznacznie umiejetnosc w koncentrowaniu swoich magicznych zdolnosci, minimalnie umiejetnosci ze wszystkich szkol magii oraz nieznacznie maksymalna mane",
        "effects": [
            ["_pb_skill", 310, 10],
            ["_pb_skill_magic_all", 5],
            ["_pb_mana", 300],
        ],
    },
    {
        "name": "specjalista",
        "cost": 40,
        "runes": ["Shael", "Io", "Sol"],
        "description": "podnosi nieznacznie ilosc wyprowadzanych atakow specjalnych",
        "effects": [
            ["_pb_prop", "_live_i_special_attack_quickness", 15],
        ],
    },
    {
        "name": "kaplan bitewny",
        "cost": 40,
        "runes": ["Dol", "Tir", "Io"],
        "description": "podnosi minimalnie umiejetnosc w poslugiwaniu sie magia zycia, nieznacznie umiejetnosc w koncentrowaniu swoich magicznych zdolnosci podczas walki, minimalnie umiejetnosc w unikaniu ciosow przeciwnika, minimalnie umiejetnosc w parowaniu ciosow przeciwnika oraz minimalnie umiejetnosc w skutecznym uzywaniu tarczy ponadto pozwala uzywac tarczy, parowac i unikac podczas czarowania",
        "effects": [
            ["_pb_skill", 304, 5],
            ["_pb_skill", 311, 10],
            ["_pb_skill", 24, 5],
            ["_pb_skill", 23, 5],
            ["_pb_skill", 26, 5],
            ["_pb_prop", "_live_i_concentrate_use_defense", 1],
        ],
    },
    {
        "name": "zdrada",
        "cost": 10,
        "runes": ["Io", "Tal", "El"],
        "description": "podnosi minimalnie inteligencje ponadto zamienia ze soba umiejetnosci w poslugiwaniu sie magia zycia i w poslugiwaniu sie magia mroku",
        "effects": [
            ["_pb_stat", 3, 5],
            ["_pb_skill_swap", 304, 305],
        ],
    },
    {
        "name": "podmiana",
        "cost": 10,
        "runes": ["Eld", "Io", "Thul"],
        "description": "podnosi minimalnie sile ponadto zamienia ze soba umiejetnosci w skutecznym uzywaniu tarczy i w walce dwiema bronmi jednoczesnie",
        "effects": [
            ["_pb_stat", 0, 5],
            ["_pb_skill_swap", 26, 20],
        ],
    },
    {
        "name": "bestia",
        "cost": 40,
        "runes": ["Hel", "El", "Dol"],
        "description": "podnosi nieznacznie umiejetnosc w walce bez broni oraz nieznacznie umiejetnosc w poslugiwaniu sie magia przemiany",
        "effects": [
            ["_pb_skill", 21, 10],
            ["_pb_skill", 332, 10],
        ],
    },
    {
        "name": "wladca bestii",
        "cost": 40,
        "runes": ["Io", "Amn", "Nef"],
        "description": "podnosi nieznacznie umiejetnosc w magii tworzenia i przywolywania natomiast obniza troche ilosc many potrzebna do utrzymania przywolancow ponadto pozwala przywolac jednego dodatkowego, innego niz juz wezwany przywolanca",
        "effects": [
            ["_pb_skill", 336, 10],
            ["_pb_prop", "_live_i_allow_extra_summons", 1],
            ["_pb_prop", "_live_i_summons_mana_usage_increased", -35],
        ],
    },
    {
        "name": "kaznodzieja",
        "cost": 40,
        "runes": ["Sol", "Hel", "Ort"],
        "description": "podnosi nieznacznie umiejetnosc w poslugiwaniu sie magia zycia, nieznacznie umiejetnosc w mistycyzmie, minimalnie madrosc, nieznacznie odpornosc na obrazenia magii smierci oraz minimalnie sile czarow leczacych",
        "effects": [
            ["_pb_skill", 304, 10],
            ["_pb_skill", 334, 10],
            ["_pb_stat", 4, 10],
            ["_pb_prop", "_obj_magic_i_res_death", 10],
            ["_pb_prop", "_live_i_spell_strenght_increased_4", 10],
        ],
    },
    {
        "name": "sila smoka",
        "cost": 60,
        "runes": ["Tal", "Dol", "Ko"],
        "description": "laczy ducha wlasciciela z duchem pradawnego smoka",
        "effects": [
            ["_pb_special", "sila smoka", "/d/Warlock/common/runes/spec_ciecie", "laczy ducha wlasciciela z duchem pradawnego smoka"],
        ],
    },
    {
        "name": "ciezkozbrojny",
        "cost": 40,
        "runes": ["Lum", "Eth", "Eld"],
        "description": "podnosi minimalnie sile, minimalnie umiejetnosci walki wszystkimi bronmi oraz minimalnie umiejetnosc w skutecznym uzywaniu tarczy natomiast obniza zauwazalnie wplyw przeciazenia na zmeczenie w walce",
        "effects": [
            ["_pb_stat", 0, 5],
            ["_pb_skill_weapon", 5],
            ["_pb_skill", 26, 5],
            ["_pb_prop", "_live_i_encumberance_swing_fatigue_increased", -50],
        ],
    },
    {
        "name": "wladca ciemnosci",
        "cost": 40,
        "runes": ["Nef", "Sol", "Io"],
        "description": "podnosi nieznacznie umiejetnosc w poslugiwaniu sie magia mroku natomiast obniza troche ilosc many potrzebna do utrzymania przywolancow ponadto pozwala przywolac jednego dodatkowego, innego niz juz wezwany przywolanca",
        "effects": [
            ["_pb_skill", 305, 10],
            ["_pb_prop", "_live_i_allow_extra_summons", 1],
            ["_pb_prop", "_live_i_summons_mana_usage_increased", -35],
        ],
    },
    {
        "name": "kamiennoskory",
        "cost": 40,
        "runes": ["Ko", "Eld", "Ith"],
        "description": "podnosi nieco odpornosc na obrazenia klute, nieco odpornosc na obrazenia ciete oraz nieco odpornosc na obrazenia obuchowe",
        "effects": [
            ["_pb_prop", "_obj_magic_i_res_impale", 18],
            ["_pb_prop", "_obj_magic_i_res_slash", 18],
            ["_pb_prop", "_obj_magic_i_res_bludgeon", 18],
        ],
    },
    {
        "name": "antymagia",
        "cost": 40,
        "runes": ["Ort", "Ko", "El"],
        "description": "podnosi zauwazalnie odpornosc na obrazenia magii powietrza, zauwazalnie odpornosc na obrazenia magii ziemi, zauwazalnie odpornosc na obrazenia magii ognia, zauwazalnie odpornosc na obrazenia magii wody, zauwazalnie odpornosc na obrazenia magii zycia oraz zauwazalnie odpornosc na obrazenia magii smierci",
        "effects": [
            ["_pb_prop", "_obj_magic_i_res_air", 40],
            ["_pb_prop", "_obj_magic_i_res_earth", 40],
            ["_pb_prop", "_obj_magic_i_res_fire", 40],
            ["_pb_prop", "_obj_magic_i_res_water", 40],
            ["_pb_prop", "_obj_magic_i_res_life", 40],
            ["_pb_prop", "_obj_magic_i_res_death", 40],
        ],
    },
    {
        "name": "lekkozbrojny",
        "cost": 40,
        "runes": ["Eld", "Ral", "Lum"],
        "description": "podnosi minimalnie zrecznosc, minimalnie umiejetnosci walki wszystkimi bronmi, minimalnie umiejetnosc w unikaniu ciosow przeciwnika, ogromnie wplyw przeciazenia na zmeczenie w walce, bardzo ilosc przeciwnikow z ktorymi mozemy walczyc bez utraty sprawnosci oraz minimalnie ilosc obrazen ktore pomijaja zbroje",
        "effects": [
            ["_pb_stat", 1, 5],
            ["_pb_skill_weapon", 5],
            ["_pb_skill", 24, 5],
            ["_pb_prop", "_live_i_encumberance_swing_fatigue_increased", 100],
            ["_pb_prop", "_live_i_enemy_defese_penalty_reduction", 4],
            ["_pb_prop", "_live_i_ac_penetration", 10],
        ],
    },
    {
        "name": "mistrz harmonii",
        "cost": 40,
        "runes": ["Eld", "Ko", "Shael"],
        "description": "podnosi minimalnie sile czarow wzmacniajacych oraz minimalnie sile czarow oslabiajacych natomiast obniza nieco ilosc many potrzebna do utrzymania aur ponadto pozwala utrzymywac jedna dodatkowa aure",
        "effects": [
            ["_pb_prop", "_live_i_allow_extra_aura", 1],
            ["_pb_prop", "_live_i_auras_mana_usage_increased", -30],
            ["_pb_prop", "_live_i_spell_strenght_increased_8", 5],
            ["_pb_prop", "_live_i_spell_strenght_increased_16", 5],
        ],
    },
    {
        "name": "przewrotnosc",
        "cost": 10,
        "runes": ["Tir", "Amn", "Hel"],
        "description": "podnosi minimalnie zrecznosc ponadto zamienia ze soba umiejetnosci w parowaniu ciosow przeciwnika i w unikaniu ciosow przeciwnika",
        "effects": [
            ["_pb_stat", 1, 5],
            ["_pb_skill_swap", 23, 24],
        ],
    },
    {
        "name": "wszechstronny",
        "cost": 40,
        "runes": ["Gul", "Dol", "Ral"],
        "description": "podnosi zauwazalnie wielkosc listy dozwolonych czarow, nieznacznie umiejetnosc w poslugiwaniu sie magia ognia, nieznacznie umiejetnosc w poslugiwaniu sie magia wody, nieznacznie umiejetnosc w poslugiwaniu sie magia ziemi oraz nieznacznie umiejetnosc w poslugiwaniu sie magia powietrza natomiast obniza troche koszt czarow, nieco szybkosc odnawiania czarow oraz minimalnie szybkosc czarowania",
        "effects": [
            ["_pb_prop", "_live_i_spell_mana_increased", -40],
            ["_pb_prop", "_live_i_spell_rest_decreased", -100],
            ["_pb_prop", "_live_i_spell_cast_decreased", -10],
            ["_pb_prop", "_live_i_extra_auto_cast", 5],
            ["_pb_skill", 300, 8],
            ["_pb_skill", 303, 8],
            ["_pb_skill", 302, 8],
            ["_pb_skill", 301, 8],
        ],
    },
    {
        "name": "wampir",
        "cost": 40,
        "runes": ["Tal", "Hel", "Gul"],
        "description": "podnosi troche ilosc zycia wykradanego przy atakach ponadto sprawia ze nie mozesz byc magicznie uleczony",
        "effects": [
            ["_pb_prop", "_live_i_life_steal", 40],
            ["_pb_prop", "_live_i_cannot_be_healed", 1],
        ],
    },
    {
        "name": "sama magia",
        "cost": 40,
        "runes": ["Lum", "Ist", "Eld"],
        "description": "podnosi minimalnie szybkosc odnawiania czarow oraz minimalnie szybkosc czarowania natomiast obniza nieznacznie koszt czarow, ogromnie szybkosc wyprowadzanych atakow oraz ogromnie ilosc wyprowadzanych atakow specjalnych",
        "effects": [
            ["_pb_prop", "_live_i_spell_mana_increased", -15],
            ["_pb_prop", "_live_i_spell_rest_decreased", 20],
            ["_pb_prop", "_live_i_spell_cast_decreased", 20],
            ["_pb_prop", "_live_i_quickness", -1000],
            ["_pb_prop", "_live_i_special_attack_quickness", -1000],
        ],
    },
    {
        "name": "cien",
        "cost": 40,
        "runes": ["Fal", "Thul", "Vex"],
        "description": "podnosi nieznacznie ilosc obrazen ktore pomijaja odpornosci, nieco ilosc obrazen ktore pomijaja zbroje, ogromnie wplyw wagi zbroi na szybkosc walki oraz ogromnie wplyw wagi zbroi na czarowanie natomiast obniza nieco odpornosc na obrazenia klute, nieco odpornosc na obrazenia ciete, nieco odpornosc na obrazenia obuchowe, nieco odpornosc na obrazenia magii powietrza, nieco odpornosc na obrazenia magii ziemi, nieco odpornosc na obrazenia magii ognia, nieco odpornosc na obrazenia magii wody, nieco odpornosc na obrazenia magii zycia oraz nieco odpornosc na obrazenia magii smierci",
        "effects": [
            ["_pb_prop", "_live_i_resistance_penetration", 20],
            ["_pb_prop", "_live_i_ac_penetration", 30],
            ["_pb_prop", "_live_i_fight_armour_weight_increased", 100],
            ["_pb_prop", "_live_i_mage_armour_weight_increased", 500],
            ["_pb_prop", "_obj_magic_i_res_impale", -25],
            ["_pb_prop", "_obj_magic_i_res_slash", -25],
            ["_pb_prop", "_obj_magic_i_res_bludgeon", -25],
            ["_pb_prop", "_obj_magic_i_res_air", -25],
            ["_pb_prop", "_obj_magic_i_res_earth", -25],
            ["_pb_prop", "_obj_magic_i_res_fire", -25],
            ["_pb_prop", "_obj_magic_i_res_water", -25],
            ["_pb_prop", "_obj_magic_i_res_life", -25],
            ["_pb_prop", "_obj_magic_i_res_death", -25],
        ],
    },
]
